version: 2
jobs:
  build:
    context: aws_keys
    docker:
      - image: circleci/node:8.11
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: install dependencies
          command: 'npm install'

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: test
          command: 'npm test'

      - run:
          name: build
          command: 'npm run build'

      - run:
          name: Echo env variables
          command: |
            echo $AWS_ACCESS_KEY_ID
            echo $AWS_SECRET_ACCESS_KEY

      - run:
          name: Create s3 bucket
          command: |
            sudo apt-get -y -qq install awscli
            aws s3 mb s3://${CIRCLE_BRANCH}-{CIRCLE_BUILD_NUM}

      - run:
          name: Deploy
          command: 'aws s3 sync build/ s3://${CIRCLE_BRANCH}-{CIRCLE_BUILD_NUM} --delete'

#  deploy:
#    context: aws_keys
#    machine:
#      enabled: true
#    steps:
#      - run:
#          name: Echo env variables
#          command: 'echo $AWS_ACCESS_KEY_ID, $AWS_SECRET_ACCESS_KEY'
#      - run:
#          name: Create s3 bucket
#          command: 'aws s3 mb s3://${CIRCLE_BRANCH}-{CIRCLE_BUILD_NUM}'
#      - run:
#          name: Deploy
#          command: 'aws s3 sync build/ s3://${CIRCLE_BRANCH}-{CIRCLE_BUILD_NUM} --delete'