version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.18
jobs:
  build_project:
    docker:
      - image: circleci/node:8.11
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: install dependencies
          command: 'npm install'
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: test
          command: 'npm test'
      - run:
          name: build
          command: 'npm run build'
      - persist_to_workspace:
          root: .
          paths:
            - .
  s3_bucket_create_deploy:
    executor: aws-cli/default
    steps:
      - attach_workspace:
          at: .
      - aws-cli/setup:
          profile-name: default
      - run:
          name: Create s3 bucket
          command: aws s3 mb s3://${CIRCLE_BRANCH}-${CIRCLE_BUILD_NUM}
      - run:
          name: Upload file to S3
          command: aws s3 sync ./build/ s3://${CIRCLE_BRANCH}-${CIRCLE_BUILD_NUM} --delete
  deploy_cloudfront:
      executor: aws-cli/default
      steps:
        - attach_workspace:
            at: .
        - aws-cli/setup:
            profile-name: default
        - run:
            name: Create cloudfront distribution
            command: aws cloudfront create-distribution --origin-domain-name ${CIRCLE_BRANCH}-${CIRCLE_PREVIOUS_BUILD_NUM}.s3.amazonaws.com --default-root-object index.html

workflows:
  version: 2
  build:
    jobs:
      - build_project
      - s3_bucket_create_deploy:
          requires:
            - build_project
          context: aws_mck_context
      - deploy_cloudfront:
          requires:
            - s3_bucket_create_deploy
          context: aws_mck_context