version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11
    steps:
      - checkout
      - run:
          name: install dependencies
          command: 'npm install'
      - run:
          name: build
          command: 'npm build'
  deploy:
    machine:
      enabled: true
    context: AWS_CREDENTIALS
    steps:
      - run:
          name: "Create s3 bucket"
          command: 'aws s3 mb s3://${CIRCLE_BRANCH}-{CIRCLE_BUILD_NUM}'
      - run:
          name: Deploy
          command: 'aws s3 sync build/ s3://${CIRCLE_BRANCH}-{CIRCLE_BUILD_NUM} --delete'