version: 2
jobs:
  build:
    docker:
      - image: node:8.0.0
    working_directory: ~/circle-tmp-folder
    steps:
          - run:
          name: install dependencies
          command: 'npm install'
          name: build
            command: 'npm build'
  deploy:
    machine:
      enabled: true
    working_directory: ~/circle-tmp-folder
    steps:
      - run:
          name: Deploy
          command: 'aws s3 sync ${source}/ s3://${bucket} --region us-west-2'