version: 2.0
jobs:
  build_project:
    docker:
      - image: circleci/node:8.11
      - image: circleci/aws-cli@0.1.18
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: install dependencies
          command: 'npm install'
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: test
          command: 'npm test'
      - run:
          name: build
          command: 'npm run build'
      - run:
          name: create version file
          command: echo ${CIRCLE_BUILD_NUM} > LIVE.txt
      - persist_to_workspace:
          root: .
          paths:
            - .
      - attach_workspace:
          at: .
      - run:
          name: Upload assests to S3
          command: aws s3 sync ./build/ s3://finlab-deploys/${CIRCLE_PROJECT_REPONAME}/${CIRCLE_BRANCH}/${CIRCLE_BUILD_NUM}/
      - run:
          name: Upload version file to S3
          command: |
            ls -al
            pwd
            aws s3 cp LIVE.txt s3://finlab-deploys/${CIRCLE_PROJECT_REPONAME}/${CIRCLE_BRANCH}/LIVE.txt

workflows:
  version: 2
  build:
    jobs:
      - build_project
      - s3_bucket_create_deploy:
          requires:
            - build_project
          context: aws_mck_context
